version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: ${APP_NAME}_${ENV}_db
    restart: unless-stopped
    networks:
      - network
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "app" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db:
    name: ${APP_NAME}_${ENV}_db

networks:
  network:
    name: ${APP_NAME}_${ENV}
    driver: bridge
