version: "3"

dotenv:
  - .env

vars:
  BUILD_FLAGS: -s -w -X 'main.buildName={{.APP_NAME}}' -X 'main.buildVer={{.APP_VERSION}}/{{ARCH}}'

tasks:
  run:
    desc: Run the application
    cmds:
      - go run -race -ldflags "{{.BUILD_FLAGS}}" main.go {{.CLI_ARGS}}

  gen:
    desc: Generate code
    cmds:
      - task: gen.proto

  gen.proto:
    desc: Generate protobuf code
    cmds:
      - rm -rvf ./sdk/proto
      - buf lint proto
      - buf generate

  migrate:
    desc: Apply db migrations
    cmds:
      - go run -ldflags "{{.BUILD_FLAGS}}" main.go --migrate-up {{.CLI_ARGS}}

  demigrate:
    desc: Revert db migrations
    cmds:
      - go run -ldflags "{{.BUILD_FLAGS}}" main.go --migrate-down {{.CLI_ARGS}}
