// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/a23n/v1/auth.proto

package v1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/ashep/a23n/sdk/proto/a23n/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "a23n.v1.AuthService"
)

// AuthServiceClient is a client for the a23n.v1.AuthService service.
type AuthServiceClient interface {
	Authenticate(context.Context, *connect_go.Request[v1.AuthenticateRequest]) (*connect_go.Response[v1.AuthenticateResponse], error)
	Authorize(context.Context, *connect_go.Request[v1.AuthorizeRequest]) (*connect_go.Response[v1.AuthorizeResponse], error)
	CreateEntity(context.Context, *connect_go.Request[v1.CreateEntityRequest]) (*connect_go.Response[v1.CreateEntityResponse], error)
	UpdateEntity(context.Context, *connect_go.Request[v1.UpdateEntityRequest]) (*connect_go.Response[v1.UpdateEntityResponse], error)
	GetEntity(context.Context, *connect_go.Request[v1.GetEntityRequest]) (*connect_go.Response[v1.GetEntityResponse], error)
}

// NewAuthServiceClient constructs a client for the a23n.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		authenticate: connect_go.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+"/a23n.v1.AuthService/Authenticate",
			opts...,
		),
		authorize: connect_go.NewClient[v1.AuthorizeRequest, v1.AuthorizeResponse](
			httpClient,
			baseURL+"/a23n.v1.AuthService/Authorize",
			opts...,
		),
		createEntity: connect_go.NewClient[v1.CreateEntityRequest, v1.CreateEntityResponse](
			httpClient,
			baseURL+"/a23n.v1.AuthService/CreateEntity",
			opts...,
		),
		updateEntity: connect_go.NewClient[v1.UpdateEntityRequest, v1.UpdateEntityResponse](
			httpClient,
			baseURL+"/a23n.v1.AuthService/UpdateEntity",
			opts...,
		),
		getEntity: connect_go.NewClient[v1.GetEntityRequest, v1.GetEntityResponse](
			httpClient,
			baseURL+"/a23n.v1.AuthService/GetEntity",
			opts...,
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	authenticate *connect_go.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	authorize    *connect_go.Client[v1.AuthorizeRequest, v1.AuthorizeResponse]
	createEntity *connect_go.Client[v1.CreateEntityRequest, v1.CreateEntityResponse]
	updateEntity *connect_go.Client[v1.UpdateEntityRequest, v1.UpdateEntityResponse]
	getEntity    *connect_go.Client[v1.GetEntityRequest, v1.GetEntityResponse]
}

// Authenticate calls a23n.v1.AuthService.Authenticate.
func (c *authServiceClient) Authenticate(ctx context.Context, req *connect_go.Request[v1.AuthenticateRequest]) (*connect_go.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// Authorize calls a23n.v1.AuthService.Authorize.
func (c *authServiceClient) Authorize(ctx context.Context, req *connect_go.Request[v1.AuthorizeRequest]) (*connect_go.Response[v1.AuthorizeResponse], error) {
	return c.authorize.CallUnary(ctx, req)
}

// CreateEntity calls a23n.v1.AuthService.CreateEntity.
func (c *authServiceClient) CreateEntity(ctx context.Context, req *connect_go.Request[v1.CreateEntityRequest]) (*connect_go.Response[v1.CreateEntityResponse], error) {
	return c.createEntity.CallUnary(ctx, req)
}

// UpdateEntity calls a23n.v1.AuthService.UpdateEntity.
func (c *authServiceClient) UpdateEntity(ctx context.Context, req *connect_go.Request[v1.UpdateEntityRequest]) (*connect_go.Response[v1.UpdateEntityResponse], error) {
	return c.updateEntity.CallUnary(ctx, req)
}

// GetEntity calls a23n.v1.AuthService.GetEntity.
func (c *authServiceClient) GetEntity(ctx context.Context, req *connect_go.Request[v1.GetEntityRequest]) (*connect_go.Response[v1.GetEntityResponse], error) {
	return c.getEntity.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the a23n.v1.AuthService service.
type AuthServiceHandler interface {
	Authenticate(context.Context, *connect_go.Request[v1.AuthenticateRequest]) (*connect_go.Response[v1.AuthenticateResponse], error)
	Authorize(context.Context, *connect_go.Request[v1.AuthorizeRequest]) (*connect_go.Response[v1.AuthorizeResponse], error)
	CreateEntity(context.Context, *connect_go.Request[v1.CreateEntityRequest]) (*connect_go.Response[v1.CreateEntityResponse], error)
	UpdateEntity(context.Context, *connect_go.Request[v1.UpdateEntityRequest]) (*connect_go.Response[v1.UpdateEntityResponse], error)
	GetEntity(context.Context, *connect_go.Request[v1.GetEntityRequest]) (*connect_go.Response[v1.GetEntityResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/a23n.v1.AuthService/Authenticate", connect_go.NewUnaryHandler(
		"/a23n.v1.AuthService/Authenticate",
		svc.Authenticate,
		opts...,
	))
	mux.Handle("/a23n.v1.AuthService/Authorize", connect_go.NewUnaryHandler(
		"/a23n.v1.AuthService/Authorize",
		svc.Authorize,
		opts...,
	))
	mux.Handle("/a23n.v1.AuthService/CreateEntity", connect_go.NewUnaryHandler(
		"/a23n.v1.AuthService/CreateEntity",
		svc.CreateEntity,
		opts...,
	))
	mux.Handle("/a23n.v1.AuthService/UpdateEntity", connect_go.NewUnaryHandler(
		"/a23n.v1.AuthService/UpdateEntity",
		svc.UpdateEntity,
		opts...,
	))
	mux.Handle("/a23n.v1.AuthService/GetEntity", connect_go.NewUnaryHandler(
		"/a23n.v1.AuthService/GetEntity",
		svc.GetEntity,
		opts...,
	))
	return "/a23n.v1.AuthService/", mux
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Authenticate(context.Context, *connect_go.Request[v1.AuthenticateRequest]) (*connect_go.Response[v1.AuthenticateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("a23n.v1.AuthService.Authenticate is not implemented"))
}

func (UnimplementedAuthServiceHandler) Authorize(context.Context, *connect_go.Request[v1.AuthorizeRequest]) (*connect_go.Response[v1.AuthorizeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("a23n.v1.AuthService.Authorize is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateEntity(context.Context, *connect_go.Request[v1.CreateEntityRequest]) (*connect_go.Response[v1.CreateEntityResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("a23n.v1.AuthService.CreateEntity is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateEntity(context.Context, *connect_go.Request[v1.UpdateEntityRequest]) (*connect_go.Response[v1.UpdateEntityResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("a23n.v1.AuthService.UpdateEntity is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetEntity(context.Context, *connect_go.Request[v1.GetEntityRequest]) (*connect_go.Response[v1.GetEntityResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("a23n.v1.AuthService.GetEntity is not implemented"))
}
