on: [ push ]
env:
  APP_NAME: a23n
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run:
          - go mod vendor
          - go install github.com/rakyll/gotest
      - name: run
        run:
          - gotest -v ./...

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: login
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME .
      - name: tag-latest
        if: github.ref_name == 'master'
        run: docker tag ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:latest
      - name: push
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME
      - name: push-latest
        if: github.ref_name == 'master'
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:latest
