on: [ push ]
env:
  APP_NAME: a23n
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup
        name: Install dependencies
        run: |
          go install github.com/rakyll/gotest@latest
          go mod vendor
      - id: run
        name: Run tests
        run: gotest -v ./...

  publish-image:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - id: login
        name: Docker login
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: build
        name: Build
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME .
      - id: tag-latest
        name: Add latest tag to the image
        if: github.ref_name == 'master'
        run: docker tag ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:latest
      - id: push
        name: Push image to the registry
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:$GITHUB_REF_NAME
      - id: push-latest
        name: Push latest tag to the registry
        if: github.ref_name == 'master'
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/$APP_NAME:latest
